Repository h5py/h5py, pull requests merged in 2019-11, with the labels that each got.

#1430 Abbreviate intro to low-level API docs
  docs_api/index.rst
Labels: documentation

#1424 TST,CI: Run rever check on CI to reduce release friction
  .authors.yml
  azure-pipelines.yml
  tox.ini
Labels: ci

#1442 Introduction to what 'Parallel HDF5' is
  docs/mpi.rst
Labels: documentation

#1333 Added chunk iteration class
  docs/high/dataset.rst
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/chunkiter.rst
Labels: enhancement
