Repository h5py/h5py, pull requests merged in 2019-09, with the labels that each got.

#1250 Add recently merged PRs to release notes
  news/existing.rst
Labels: documentation

#1331 Dataset doc: add warning about __setitem function
  docs/high/dataset.rst
Labels: documentation

#1345 Fix getting maxshape on empty datasets
  h5py/_hl/dataset.py
  h5py/tests/conftest.py
  h5py/tests/test_dataset.py
  news/empty-maxshape.rst
Labels: bug

#1334 Allow dset.astype() to be indexed, not only used as a context manager
  docs/high/dataset.rst
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/astype-wrapper.rst
Labels: enhancement

#1301 initial release guide
  docs/index.rst
  docs/release_guide.rst
Labels: documentation

#1335 Hdf5 1.11.6 (pre-release 1.12.0)
  api_gen.py
  h5py/_hl/files.py
  h5py/_proxy.pyx
  h5py/api_functions.txt
  h5py/api_types_hdf5.pxd
  h5py/h5f.pyx
  h5py/h5i.pyx
  h5py/h5o.pyx
  h5py/h5s.pyx
  h5py/h5t.pyx
  h5py/tests/test_dataset.py
  h5py/tests/test_dataset_swmr.py
  h5py/tests/test_file.py
  h5py/tests/test_group.py
  h5py/tests/test_h5p.py
  news/HDF5_prerelease12.0
  setup_build.py
Labels: ci

#1317 More efficient handling of scalar assignments.
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/scalar_assignment.rst
Labels: enhancement

#1324 CI: Add azure pipelines ci
  azure-pipelines.yml
  ci/appveyor/get_hdf5.py
  ci/azure-pipelines-steps.yml
Labels: ci

#1347 Updated links in README.rst to use https
  README.rst
Labels: documentation

#1354 Updated h5 URL
  docs_api/index.rst
Labels: documentation
