Repository h5py/h5py, pull requests merged in 2019-10, with the labels that each got.

#1366 Remove long-deprecated dtype functions
  h5py/__init__.py
  h5py/h5t.pyx
  news/rm-deprec-dtype-funcs.rst
Labels: api changes

#1361 Special dtypes API changed in 2.10, not 2.9
  docs/special.rst
Labels: documentation

#1362 Publish API docs from Travis to Github pages
  .travis.yml
  MANIFEST.in
  docs_api/_static/.keep
  docs_api/automod.py
  github_deploy_key_h5py_h5py.enc
  h5py/h5f.pyx
  tox.ini
Labels: ci, documentation

#1379 Document testing & release notes for contributors
  .github/pull_request_template.md
  docs/contributing.rst
Labels: documentation

#1377 Publish api docs built from master
  .travis.yml
Labels: ci, documentation

#1378 Remove deprecated File.fid attribute
  h5py/_hl/files.py
  h5py/tests/test_file.py
  news/rm-file-fid.rst
Labels: api changes

#1375 Drop some of the appveyor tests
  appveyor.yml
  azure-pipelines.yml
Labels: ci

#1382 Set environment variables for ccache under pip
  setup_build.py
Labels: enhancement

#1376 Drop unneeded travis tests
  .travis.yml
  azure-pipelines.yml
Labels: ci

#1386 Remove deprecated Dataset.value attribute
  h5py/_hl/dataset.py
  h5py/_hl/files.py
  h5py/tests/test_dataset.py
  h5py/tests/test_file.py
  news/rm-dataset-value.rst
Labels: api changes

#1401 Don't fail CI on random codecov errors
  ci/upload_coverage.py
Labels: ci

#1407 Try to document reference dtypes more clearly
  docs/refs.rst
Labels: documentation

#1416 CI,DOC: Add azure status to README
  README.rst
Labels: documentation

#1420 Add a few tests for writing vlen string datasets
  h5py/tests/test_dataset.py
Labels: string/unicode usage

#1402 Cache some properties on Dataset
  h5py/_hl/base.py
  h5py/_hl/dataset.py
  h5py/_hl/group.py
  h5py/_hl/selections.py
  setup.py
Labels: enhancement

#1339 Allow storing datetime & timedelta data in HDF5 opaque types
  docs/faq.rst
  docs/special.rst
  examples/store_datetimes.py
  h5py/__init__.py
  h5py/h5t.pyx
  h5py/tests/test_dtype.py
  news/opaque-dtype.rst
Labels: enhancement

#1413 Publish unversioned API docs
  .travis.yml
Labels: ci, documentation
