Repository h5py/h5py, pull requests merged in 2020-10, with the labels that each got.

#1643 Document supplement
  docs/high/dataset.rst
  examples/bytesio.py
  h5py/_hl/group.py
  h5py/h5a.pyx
  h5py/h5g.pyx
Labels: documentation

#1674 Build & test wheels on Azure pipelines
  azure-pipelines.yml
  ci/appveyor/get_hdf5.py
  ci/azure-pipelines-steps.yml
  ci/azure-pipelines-test-wheels.yml
  ci/azure-pipelines-wheels.yml
  ci/bundle_hdf5_whl.py
  ci/fix_paths.py
  ci/travis/get_hdf5_if_needed.sh
  setup.py
  tox.ini
Labels: ci

#1689 Added function to allow unlimited resizing for VDS
  .authors.yml
  .gitignore
  docs/vds.rst
  h5py/__init__.py
  h5py/_hl/vds.py
  h5py/tests/test_vds/test_highlevel_vds.py
  news/vds-unlimited-axis.rst
Labels: vds

#1694 Don't install cibuildwheel for test jobs
  ci/azure-pipelines-steps.yml
Labels: ci

#1699 Minor documentation fixes
  docs/high/dataset.rst
  docs/high/file.rst
Labels: documentation

#1705 Use BaseTest.setUp() in TestMapping. Resolves #1700
  h5py/tests/test_base.py
Labels: MPI

#1704 Point to alternatives to using Python file-like objects
  docs/high/file.rst
Labels: documentation

#1708 Fix example of correctly reading fixed-length string attribute
  docs/strings.rst
Labels: documentation

#1710 Highlight incompatibility of changes to string conversion
  docs/whatsnew/3.0.rst
Labels: documentation

#1715 Explain more about news entries on PRs
  .github/pull_request_template.md
  docs/contributing.rst
Labels: documentation

#1718 Use cached build of HDF5 on Mac CI
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  ci/azure-pipelines-steps.yml
  ci/azure-pipelines-wheels.yml
  ci/get_hdf5_if_needed.sh
  ci/get_hdf5_win.py
Labels: ci

#1690 Set up CI for Python 3.9
  azure-pipelines.yml
  setup.py
  tox.ini
Labels: ci

#1726 Document recommended patterns for accessing fields in compound data
  docs/high/dataset.rst
Labels: documentation
