Repository h5py/h5py, pull requests merged in 2020-07, with the labels that each got.

#1589 Add some function or method docstring
  h5py/_hl/dataset.py
  h5py/_hl/files.py
Labels: documentation

#1567 Read HDF5 strings as bytes, add dataset.asstr() wrapper to get strings
  h5py/_conv.pyx
  h5py/_hl/attrs.py
  h5py/_hl/dataset.py
  h5py/_hl/dims.py
  h5py/tests/test_attrs_data.py
  h5py/tests/test_dataset.py
  h5py/tests/test_h5f.py
Labels: api changes

#1595 Fix error assigning to a fancy-indexed selection
  h5py/_selector.pyx
  h5py/tests/test_dataset.py
Labels: bug
