Repository h5py/h5py, pull requests merged in 2020-09, with the labels that each got.

#1642 Fix reporting errors from fileobj driver
  docs/high/file.rst
  h5py/h5fd.pyx
  h5py/tests/test_file2.py
Labels: bug

#1665 Require a dtype in VirtualLayout
  docs/vds.rst
  h5py/_hl/dataset.py
  h5py/_hl/vds.py
  h5py/tests/test_vds/test_lowlevel_vds.py
  news/virtuallayout-no-default-dtype.rst
Labels: api changes, enhancement

#1657 Make arrays contiguous prior to H5T conversion
  h5py/_conv.pyx
  h5py/tests/test_dataset.py
  news/non-contiguous-arrays.rst
Labels: bug, vlen

#1671 Add missing module h5ds in low-level API reference
  docs_api/h5ds.rst
  docs_api/h5fd.rst
  docs_api/index.rst
Labels: documentation

#1676 Add missing docstrings in h5py.h5ds
  docs_api/h5ds.rst
  h5py/h5ds.pyx
Labels: documentation
