Repository h5py/h5py, pull requests merged in 2020-01, with the labels that each got.

#1472 Fix doc markup for track_order parameter
  docs/high/file.rst
  docs/high/group.rst
Labels: documentation

#1481 Fix object location for intersphinx
  docs/high/attr.rst
  docs/high/dataset.rst
  docs/high/file.rst
  docs/high/group.rst
  docs/special.rst
  docs/vds.rst
Labels: documentation

#1482 Fixes for empty region references
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/empty-regionrefs.rst
Labels: bug

#1483 Allow dtype promotion in fast read pathway
  h5py/_hl/dataset.py
  h5py/_reader.pyx
Labels: enhancement
