Repository h5py/h5py, pull requests merged in 2020-08, with the labels that each got.

#1603 Stricter rules for writing into vlen string datasets
  h5py/_conv.pyx
  h5py/tests/test_dataset.py
Labels: api changes

#1613 Update documentation for strings
  docs/high/dataset.rst
  docs/special.rst
  docs/strings.rst
Labels: documentation, string/unicode usage

#1609 Fix creating datasets from nested lists of str/bytes objects & writing to fixed UTF-8 datasets
  h5py/_hl/base.py
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
Labels: bug

#1615 Add current version and build date to API docs
  docs_api/conf.py
  docs_api/index.rst
Labels: documentation

#1632 Add overview of the low-level API in the main docs
  docs/conf.py
  docs/high/lowlevel.rst
  docs/index.rst
Labels: documentation

#1624 Fix cross-reference of constants in API docs
  h5py/_objects.pyx
  h5py/h5f.pyx
Labels: documentation

#1608 Be less strict about convert to/from vlen strings
  MANIFEST.in
  h5py/_conv.pyx
  h5py/h5t.pxd
  h5py/h5t.pyx
  h5py/tests/data_files/__init__.py
  h5py/tests/data_files/vlen_string_dset.h5
  h5py/tests/data_files/vlen_string_dset_utc.h5
  h5py/tests/test_dataset.py
  setup.py
Labels: string/unicode usage

#1628 Add explanation around HDF5 encodings
  docs/strings.rst
Labels: documentation

#1637 Add missing objects to H5P API docs
  docs_api/h5d.rst
  docs_api/h5p.rst
  h5py/h5p.pyx
Labels: documentation

#1633 Update Windows CI to newer HDF5
  appveyor.yml
  azure-pipelines.yml
  ci/appveyor/get_hdf5.py
  h5py/_hl/compat.py
  h5py/tests/test_h5d_direct_chunk.py
  news/utf8-windows.rst
Labels: ci

#1629 Add allow_unknown_filter
  docs/high/group.rst
  h5py/_hl/dataset.py
  h5py/_hl/filters.py
  h5py/_hl/group.py
  h5py/tests/test_dataset.py
  news/allow-unknown-filter.rst
Labels: enhancement
