Repository h5py/h5py, pull requests merged in 2020-06, with the labels that each got.

#1535 Make creating a new dataset from strings/bytes more consistent
  h5py/_hl/attrs.py
  h5py/_hl/base.py
  h5py/_hl/dataset.py
  h5py/_hl/group.py
  h5py/tests/test_dataset.py
  news/assign-list-of-strings.rst
Labels: api changes

#1570 Document how & when h5py closes files
  docs/high/file.rst
Labels: documentation

#1576 Update the docs of meta-data cache config functions
  h5py/h5f.pyx
Labels: documentation

#1574 Fix writing Python integers as uint64
  h5py/_hl/attrs.py
  h5py/_hl/base.py
  h5py/_hl/dataset.py
  h5py/tests/test_attrs.py
  h5py/tests/test_dataset.py
Labels: bug
