Repository h5py/h5py, pull requests merged in 2021-01, with the labels that each got.

#1785 docs: fix simple typo, explictly -> explicitly
  docs/strings.rst
Labels: documentation

#1789 Deprecate setting default_file_mode to values other than 'r'
  h5py/h5.pyx
  news/default-file-mode-r.rst
Labels: api changes

#1788 Move low-level API docs creation to Github actions
  .github/workflows/lowlevel-api-docs.yml
  .travis.yml
Labels: ci, documentation

#1790 Add CNAME file after building docs on Github Actions
  .github/workflows/lowlevel-api-docs.yml
Labels: ci, documentation

#1791 Fix chunk_iter mistake
  docs/high/dataset.rst
Labels: documentation

#1796 Fix read_direct when source and destination have different shapes
  .authors.yml
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/read-write-direct-fix.rst
Labels: bug
