Repository h5py/h5py, pull requests merged in 2021-06, with the labels that each got.

#1896 Add example of write_direct_chunk with DEFLATE compressed data
  examples/write-direct-compressed.py
Labels: documentation

#1902 Improve errors when opening files in append mode
  h5py/_hl/files.py
  h5py/tests/test_file.py
  news/append-filenotfound.rst
Labels: enhancement

#1903 Use Ubuntu 20.04 on Azure pipelines
  azure-pipelines.yml
  ci/azure-pipelines-steps.yml
  setup.py
  tox.ini
Labels: ci

#1889 Add default cast from H5T_NATIVE_B8 to uint8
  .authors.yml
  docs/faq.rst
  h5py/_conv.pyx
  h5py/api_types_hdf5.pxd
  h5py/h5t.pyx
  h5py/tests/test_dtype.py
  news/1258-default-cast-b8.rst
Labels: enhancement

#1839 Deprecate setting default_file_mode, only allow setting to 'r'
  h5py/_hl/files.py
  h5py/h5.pyx
  news/deprecate-default-file-mode-2.rst
Labels: api changes

#1905 Improvements to assembling virtual datasets
  docs/high/group.rst
  h5py/_hl/dataset.py
  h5py/_hl/group.py
  h5py/_hl/vds.py
  h5py/tests/test_vds/test_highlevel_vds.py
  news/vds-set-virtual-sooner.rst
Labels: enhancement
