Repository h5py/h5py, pull requests merged in 2021-03, with the labels that each got.

#1833 Document where to get filter plugins
  docs/high/dataset.rst
Labels: documentation, enhancement

#1844 Fix File.driver when built with ROS3 enabled
  h5py/_hl/files.py
  h5py/h5fd.pyx
  news/ros3-driver-fix.rst
Labels: bug

#1840 Update cibuildwheel to 1.10.0
  ci/azure-pipelines-wheels.yml
Labels: ci

#1856 Raise ValueError when accessing a group like a dataset
  h5py/_hl/group.py
  h5py/tests/test_group.py
  news/fix-1829.rst
Labels: enhancement

#1861 [DOC] - Update README link to the HDF5 website
  .authors.yml
  README.rst
Labels: documentation

#1854 Make file closing and get_obj_ids more robust
  h5py/_hl/files.py
  h5py/h5f.pyx
  h5py/tests/test_file.py
  news/get-obj-ids-gc.rst
Labels: bug
