Repository h5py/h5py, pull requests merged in 2021-02, with the labels that each got.

#1813 Allow H5PY_TEST_CHECK_FILTERS environment variable into tox
  tox.ini
Labels: ci

#1819 Fix reading data with vlen array of fixed-length strings
  h5py/_conv.pyx
  h5py/tests/test_attrs.py
Labels: bug

#1818 Fix read_direct & write_direct with integer indices
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  h5py/tests/test_h5o.py
Labels: bug

#1816 Document that object arrays for vlen are a workaround
  docs/special.rst
Labels: documentation

#1820 Add some missing news entries
  news/read-vlen-array-s1.rst
  news/read-write-direct-w-index.rst
Labels: documentation

#1815 Create appropriate exception types when the exception message has errno
  h5py/_errors.pyx
  h5py/_hl/attrs.py
  h5py/_hl/files.py
  h5py/tests/test_dataset_getitem.py
  h5py/tests/test_file.py
Labels: api changes, enhancement

#1824 Document how to install for development
  MANIFEST.in
  dev-install.sh
  docs/build.rst
Labels: documentation

#1830 doc: add release notes for enh-ros3 branch
  news/enh-ros3.rst
Labels: documentation
