Repository h5py/h5py, pull requests merged in 2021-12, with the labels that each got.

#2016 Build HDF5 with Visual Studio 2019 on Azure CI
  azure-pipelines.yml
  ci/get_hdf5_win.py
Labels: ci

#2014 Use pre-commit.ci for pre-commit CI
  .pre-commit-config.yaml
  azure-pipelines.yml
Labels: ci

#2020 Don't re-enable garbage collection if it was disabled before
  h5py/_objects.pyx
  h5py/h5f.pyx
  news/gc-check-reenable.rst
Labels: bug

#2021 DOC: add note about file-like + threading + deadlocks
  docs/high/file.rst
Labels: documentation
