Repository h5py/h5py, pull requests merged in 2022-03, with the labels that each got.

#2066 Use simple cached_property with no locking
  h5py/_hl/base.py
  h5py/_hl/dataset.py
  news/cached-property.rst
  setup.py
Labels: bug

#2032 Don't build HDF5 tests in CI
  ci/get_hdf5_if_needed.sh
  ci/get_hdf5_win.py
Labels: ci

#2041 Expose DIRECT VFD to Linux Users that have the required support
  api_gen.py
  ci/get_hdf5_if_needed.sh
  h5py/_hl/files.py
  h5py/api_functions.txt
  h5py/api_types_hdf5.pxd
  h5py/h5.pyx
  h5py/h5fd.pyx
  h5py/h5p.pyx
  h5py/tests/test_file.py
  h5py/tests/test_h5f.py
  setup_build.py
  setup_configure.py
Labels: enhancement
