Repository h5py/h5py, pull requests merged in 2022-09, with the labels that each got.

#2148 Use macOS 11 on CI
  azure-pipelines.yml
Labels: ci

#2151 Add an `__array__()` method to the `FieldsWrapper` class
  h5py/_hl/dataset.py
  h5py/tests/test_dataset.py
  news/add_fields_array.rst
Labels: enhancement

#2149 Clarify which versions of HDF5 are supported
  docs/build.rst
  setup.py
Labels: documentation
