Repository h5py/h5py, pull requests merged in 2022-11, with the labels that each got.

#2165 Add CI/tox support for Python 3.11
  azure-pipelines.yml
  ci/azure-pipelines-wheels.yml
  tox.ini
Labels: ci

#2137 DOC: improve formatting of the locking parameter to File
  docs/Makefile
  docs/high/file.rst
  h5py/_hl/files.py
Labels: documentation

#2132 Test default fill values for some common types
  h5py/h5p.pyx
  h5py/tests/test_dataset.py
Labels: bug

#2178 Update how architectures are defined on Travis CI
  .travis.yml
Labels: ci
