Repository h5py/h5py, pull requests merged in 2023-10, with the labels that each got.

#2318 Fix `register_filter` on some architectures
  h5py/h5z.pyx
Labels: bug

#2321 Prepare release notes for 3.10
  docs/conf.py
  docs/whatsnew/3.10.rst
  docs/whatsnew/index.rst
  h5py/version.py
  news/ros3-token.rst
  news/vsource-repeated-select.rst
  setup.py
Labels: documentation

#2323 Build Python 3.12 wheels for Linux ARM64
  .travis.yml
Labels: ci

#2327 Use RTD theme for HTML docs
  azure-pipelines.yml
  docs/conf.py
  docs/requirements-rtd.txt
  tox.ini
Labels: documentation
