Repository h5py/h5py, pull requests merged in 2024-01, with the labels that each got.

#2364 Temporarily pin pytest<8 for running tests
  tox.ini
Labels: ci

#2362 [DOC] Update list of hdf5plugin supported plugins
  docs/related_projects.rst
Labels: documentation

#2358 Creates access to remaining H5O_info_t struct fields, Closes #2347
  h5py/h5o.pyx
  news/metasize_info_struct.rst
Labels: enhancement
