Repository h5py/h5py, pull requests merged in 2025-02, with the labels that each got.

#2556 BLD: fix build-time compatibility with numpy 2.3
  h5py/_conv.pyx
  h5py/utils.pyx
Labels: bug

#2517 Add File.in_memory() alternative constructor
  docs/high/file.rst
  h5py/_hl/files.py
  h5py/h5p.pyx
  h5py/tests/test_file_image.py
  news/in-memory.rst
Labels: enhancement

#2559 Prepare to release 3.13
  docs/conf.py
  docs/whatsnew/3.13.rst
  docs/whatsnew/index.rst
  h5py/h5s.pyx
  h5py/version.py
  news/h5s-select-same-shape.rst
  news/hdf5-1.14.5.rst
  news/in-memory.rst
  news/lazy_dcpl.rst
  news/views-overhaul.rst
  setup.py
Labels: documentation
